# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 23:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import runs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRunStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='finished')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
            ],
        ),
        migrations.CreateModel(
            name='ContentChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.UUIDField(verbose_name='The id from contentcuration.models.Channel')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('version', models.IntegerField(default=0)),
                ('source_domain', models.CharField(blank=True, max_length=300, null=True)),
                ('source_id', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_by_user', models.EmailField(blank=True, max_length=200, null=True)),
                ('registered_by_user_token', models.CharField(blank=True, max_length=200, null=True)),
                ('default_content_server', models.URLField(default='https://develop.contentworkshop.learningequality.org', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChannelRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chef_name', models.CharField(max_length=200)),
                ('ricecooker_version', models.CharField(blank=True, max_length=100, null=True)),
                ('logfile', models.FileField(blank=True, null=True, upload_to=runs.models.log_filename_for_run, verbose_name='Log file from the sushi chef run.')),
                ('resource_counts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('resource_sizes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extra_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('started_by_user', models.EmailField(blank=True, max_length=200, null=True)),
                ('started_by_user_token', models.CharField(blank=True, max_length=200, null=True)),
                ('content_server', models.URLField(default='https://develop.contentworkshop.learningequality.org', max_length=300)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='runs.ContentChannel')),
            ],
        ),
        migrations.AddField(
            model_name='channelrunstage',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runs.ContentChannelRun'),
        ),
    ]
