# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import runs.models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentchannelrun',
            name='logfile',
            field=models.FileField(blank=True, null=True, upload_to=runs.models.log_filename_for_run),
        ),
    ]
