# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20170608_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentchannel',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='contentchannelrun',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='contentchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentchannel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contentchannelrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentchannelrun',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
